version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: estapar_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/estacionamento
      SPRING_DATASOURCE_USERNAME: devuser
      SPRING_DATASOURCE_PASSWORD: devpass

  postgres:
    image: postgres:15
    container_name: estapar_postgres
    restart: always
    environment:
      POSTGRES_DB: estacionamento
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
