version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: estapar_postgres
    restart: always
    environment:
      POSTGRES_DB: estacionamento
      POSTGRES_USER: devuserAdmin
      POSTGRES_PASSWORD: devpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
